/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyToken__factory } from "./MyToken__factory";
export { TestToken__factory } from "./TestToken__factory";
